"use client";

import React, { useState, useMemo, useEffect, useRef } from "react";
import { ToolMeta } from "@/lib/types";
import { ToolHeader } from "../ToolHeader";
import { SEOContent } from "../SEOContent";
import { RelatedTools } from "../RelatedTools";
import { analyzeText } from "@/tools/text/wordCounter";
import { Button } from "@/components/ui/Button";
import {
  Trash2,
  Copy,
  Check,
  Sparkles,
  BookOpen,
  Volume2,
  GraduationCap,
  FileText,
  Clock,
  Hash,
  Server,
  Download,
} from "lucide-react";

export interface WordCounterViewProps {
  tool: ToolMeta;
}

export const WordCounterView: React.FC<WordCounterViewProps> = ({ tool }) => {
  const [textInput, setTextInput] = useState<string>(
    "ToolVerse is an all-in-one developer and creator toolkit providing fast, privacy-friendly online utilities. Optimize your workflow with instant text counters, converters, and security tools."
  );
  const [copied, setCopied] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);
  const [apiSynced, setApiSynced] = useState<boolean>(true);
  const [apiData, setApiData] = useState<any>(null);

  // Instant client-side analysis
  const localStats = useMemo(() => analyzeText(textInput), [textInput]);

  // Debounced API backend sync
  const debounceTimer = useRef<NodeJS.Timeout | null>(null);

  useEffect(() => {
    if (debounceTimer.current) clearTimeout(debounceTimer.current);

    debounceTimer.current = setTimeout(async () => {
      try {
        const res = await fetch("/api/text/word-counter", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text: textInput }),
        });
        if (res.ok) {
          const json = await res.json();
          if (json.success) {
            setApiData(json.data);
            setApiSynced(true);
          }
        }
      } catch (err) {
        // Silently fallback to local stats
        setApiSynced(false);
      }
    }, 250);

    return () => {
      if (debounceTimer.current) clearTimeout(debounceTimer.current);
    };
  }, [textInput]);

  const stats = apiData || {
    ...localStats,
    speakingTimeMinutes: Math.max(1, Math.ceil(localStats.words / 130)),
    fleschScore: 75,
    readingGrade: "Standard",
    syllables: localStats.words * 2,
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(textInput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyReport = () => {
    const report = `--- Text Statistics Report ---
Words: ${stats.words}
Characters: ${stats.characters}
Characters (No spaces): ${stats.charactersNoSpaces}
Sentences: ${stats.sentences}
Paragraphs: ${stats.paragraphs}
Total Lines: ${stats.lines}
Estimated Reading Time: ~${stats.readingTimeMinutes} min
Estimated Speaking Time: ~${stats.speakingTimeMinutes} min
Readability Grade: ${stats.readingGrade} (Score: ${stats.fleschScore}/100)
Avg Words/Sentence: ${stats.avgWordsPerSentence}
Avg Chars/Word: ${stats.avgCharPerWord}
Generated by ToolVerse`;

    navigator.clipboard.writeText(report);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  return (
    <div className="w-full flex flex-col gap-6">
      <ToolHeader tool={tool} />

      {/* Backend API Connection Status Banner */}
      <div className="flex items-center justify-between px-4 py-2 rounded-xl bg-surface border border-border text-xs text-text-secondary">
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
          <span className="font-semibold text-text-primary flex items-center gap-1.5">
            <Server className="w-3.5 h-3.5 text-accent" />
            Backend API Connected:
          </span>
          <span className="font-mono text-emerald-400">/api/text/word-counter</span>
        </div>
        <span className="text-[11px] text-text-tertiary hidden sm:inline">
          Real-time dual processing (Client CSPRNG + Server Analysis)
        </span>
      </div>

      {/* Hero 4-Stat Metric Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-surface border border-accent/40 p-5 rounded-2xl shadow-xl flex flex-col gap-1 relative overflow-hidden group">
          <div className="absolute top-0 right-0 w-20 h-20 bg-accent/10 rounded-full blur-2xl pointer-events-none" />
          <span className="text-xs font-bold text-accent uppercase tracking-wider flex items-center gap-1.5">
            <FileText className="w-3.5 h-3.5" /> Words
          </span>
          <span className="text-3xl sm:text-4xl font-black font-mono text-text-primary mt-1">
            {stats.words}
          </span>
          <span className="text-[11px] text-text-tertiary">Total word count</span>
        </div>

        <div className="bg-surface border border-border p-5 rounded-2xl shadow-xl flex flex-col gap-1">
          <span className="text-xs font-bold text-text-tertiary uppercase tracking-wider flex items-center gap-1.5">
            <Hash className="w-3.5 h-3.5 text-indigo-400" /> Characters
          </span>
          <span className="text-3xl sm:text-4xl font-black font-mono text-indigo-400 mt-1">
            {stats.characters}
          </span>
          <span className="text-[11px] text-text-tertiary">
            {stats.charactersNoSpaces} without spaces
          </span>
        </div>

        <div className="bg-surface border border-border p-5 rounded-2xl shadow-xl flex flex-col gap-1">
          <span className="text-xs font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1.5">
            <Clock className="w-3.5 h-3.5" /> Reading Time
          </span>
          <span className="text-3xl sm:text-4xl font-black font-mono text-emerald-400 mt-1">
            ~{stats.readingTimeMinutes} <span className="text-sm font-normal text-text-tertiary">min</span>
          </span>
          <span className="text-[11px] text-text-tertiary">Based on 200 WPM</span>
        </div>

        <div className="bg-surface border border-border p-5 rounded-2xl shadow-xl flex flex-col gap-1">
          <span className="text-xs font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1.5">
            <Volume2 className="w-3.5 h-3.5" /> Speaking Time
          </span>
          <span className="text-3xl sm:text-4xl font-black font-mono text-amber-400 mt-1">
            ~{stats.speakingTimeMinutes} <span className="text-sm font-normal text-text-tertiary">min</span>
          </span>
          <span className="text-[11px] text-text-tertiary">Based on 130 WPM speech</span>
        </div>
      </div>

      {/* Editor & Secondary Breakdown */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        {/* Left Column Text Area */}
        <div className="lg:col-span-8 flex flex-col gap-3">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <span className="text-xs font-bold text-text-secondary uppercase tracking-wider">
              Type or Paste Text Below
            </span>
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setTextInput("")}
                leftIcon={<Trash2 className="w-3.5 h-3.5 text-rose-400" />}
              >
                Clear
              </Button>
              <Button
                variant="secondary"
                size="sm"
                onClick={handleCopyReport}
                leftIcon={copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Download className="w-3.5 h-3.5" />}
              >
                {copiedReport ? "Copied Report" : "Copy Report"}
              </Button>
              <Button
                variant="primary"
                size="sm"
                onClick={handleCopy}
                leftIcon={copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
              >
                {copied ? "Copied" : "Copy Text"}
              </Button>
            </div>
          </div>
          <textarea
            value={textInput}
            onChange={(e) => setTextInput(e.target.value)}
            placeholder="Type or paste your text here to count words, characters, sentences, reading time, and keyword density..."
            rows={14}
            className="w-full bg-surface border border-border/80 focus:border-accent rounded-2xl p-5 font-sans text-sm text-text-primary outline-none resize-y leading-relaxed shadow-xl transition-all"
          />

          {/* Readability Indicator Bar */}
          <div className="bg-surface border border-border p-4 rounded-2xl shadow-md flex items-center justify-between gap-4 flex-wrap">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-accent/10 border border-accent/20 text-accent">
                <GraduationCap className="w-5 h-5" />
              </div>
              <div className="flex flex-col">
                <span className="text-xs font-bold text-text-primary">
                  Readability Ease: {stats.fleschScore}/100
                </span>
                <span className="text-[11px] text-text-tertiary">
                  Level: <strong className="text-emerald-400">{stats.readingGrade}</strong>
                </span>
              </div>
            </div>
            <div className="flex items-center gap-4 text-xs text-text-secondary font-mono">
              <span>Avg Words/Sentence: <strong>{stats.avgWordsPerSentence}</strong></span>
              <span>Avg Chars/Word: <strong>{stats.avgCharPerWord}</strong></span>
            </div>
          </div>
        </div>

        {/* Right Column Secondary Stats & Keyword Table */}
        <div className="lg:col-span-4 flex flex-col gap-6">
          <div className="bg-surface border border-border rounded-2xl p-5 shadow-xl flex flex-col gap-3 text-xs">
            <h4 className="font-bold text-text-primary text-sm border-b border-border pb-2.5 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-accent" /> Detailed Text Breakdown
            </h4>
            <div className="flex justify-between py-1.5 border-b border-border/40">
              <span className="text-text-secondary">Sentences</span>
              <span className="font-mono text-text-primary font-bold">{stats.sentences}</span>
            </div>
            <div className="flex justify-between py-1.5 border-b border-border/40">
              <span className="text-text-secondary">Paragraphs</span>
              <span className="font-mono text-text-primary font-bold">{stats.paragraphs}</span>
            </div>
            <div className="flex justify-between py-1.5 border-b border-border/40">
              <span className="text-text-secondary">Total Lines</span>
              <span className="font-mono text-text-primary font-bold">{stats.lines}</span>
            </div>
            <div className="flex justify-between py-1.5 border-b border-border/40">
              <span className="text-text-secondary">Chars (no spaces)</span>
              <span className="font-mono text-text-primary font-bold">{stats.charactersNoSpaces}</span>
            </div>
            <div className="flex justify-between py-1.5 border-b border-border/40">
              <span className="text-text-secondary">Avg Words / Sentence</span>
              <span className="font-mono text-text-primary font-bold">{stats.avgWordsPerSentence}</span>
            </div>
            <div className="flex justify-between py-1.5">
              <span className="text-text-secondary">Avg Chars / Word</span>
              <span className="font-mono text-text-primary font-bold">{stats.avgCharPerWord}</span>
            </div>
          </div>

          {/* Top Keyword Density Table */}
          {stats.topWords && stats.topWords.length > 0 && (
            <div className="bg-surface border border-border rounded-2xl p-5 shadow-xl flex flex-col gap-3 text-xs">
              <h4 className="font-bold text-text-primary text-sm border-b border-border pb-2.5 flex items-center justify-between">
                <span className="flex items-center gap-2">
                  <BookOpen className="w-4 h-4 text-accent" /> Top Keyword Density
                </span>
                <span className="text-[10px] text-text-tertiary uppercase font-mono">Freq %</span>
              </h4>
              <div className="flex flex-col gap-2">
                {stats.topWords.slice(0, 8).map((kw: any) => (
                  <div key={kw.word} className="flex items-center justify-between p-2 rounded-lg bg-surface-raised border border-border/60">
                    <span className="font-mono text-accent font-semibold">{kw.word}</span>
                    <span className="text-text-secondary font-mono text-[11px]">
                      {kw.count} <span className="text-text-tertiary">({kw.frequency}%)</span>
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>

      <SEOContent tool={tool} />
      <RelatedTools slugs={tool.related} />
    </div>
  );
};
