/**
 * ToolVerse Robots.txt Engine
 * Implements RFC 9309 (Robots Exclusion Protocol), rule generation, multi-bot grouping, path matching, and validation.
 * Pure TypeScript with zero external dependencies.
 */

export interface RobotsRuleGroup {
  id: string;
  name?: string;
  userAgents: string[];
  allows: string[];
  disallows: string[];
  crawlDelay?: number;
}

export interface RobotsConfig {
  ruleGroups: RobotsRuleGroup[];
  sitemaps: string[];
  host?: string;
}

export interface PathTestResult {
  path: string;
  userAgent: string;
  isAllowed: boolean;
  matchedRuleGroup?: string;
  matchedDirective?: 'Allow' | 'Disallow' | 'Default';
  matchedPattern?: string;
  reason: string;
}

export interface RobotsValidationIssue {
  type: 'error' | 'warning' | 'info';
  message: string;
  recommendation: string;
}

export interface RobotsValidationReport {
  isValid: boolean;
  hasTotalBlock: boolean;
  sitemapCount: number;
  ruleGroupCount: number;
  issues: RobotsValidationIssue[];
}

// ---------------- Popular Crawler Dictionaries ----------------
export const POPULAR_BOTS = {
  searchEngines: [
    { name: 'Googlebot', label: 'Google Search' },
    { name: 'Googlebot-Image', label: 'Google Images' },
    { name: 'Bingbot', label: 'Microsoft Bing' },
    { name: 'DuckDuckBot', label: 'DuckDuckGo' },
    { name: 'YandexBot', label: 'Yandex' },
    { name: 'Baiduspider', label: 'Baidu' },
    { name: 'Applebot', label: 'Apple Siri / Spotlight' },
  ],
  aiScrapers: [
    { name: 'GPTBot', label: 'OpenAI (ChatGPT)' },
    { name: 'ChatGPT-User', label: 'ChatGPT Custom Actions' },
    { name: 'CCBot', label: 'Common Crawl' },
    { name: 'ClaudeBot', label: 'Anthropic (Claude)' },
    { name: 'Claude-Web', label: 'Anthropic Web Search' },
    { name: 'Google-Extended', label: 'Google Gemini AI Training' },
    { name: 'Bytespider', label: 'ByteDance (TikTok AI)' },
    { name: 'PerplexityBot', label: 'Perplexity AI Search' },
    { name: 'cohere-ai', label: 'Cohere AI' },
  ],
  socialCrawlers: [
    { name: 'facebookexternalhit', label: 'Facebook / Meta Link Preview' },
    { name: 'Twitterbot', label: 'X / Twitter Card Crawler' },
    { name: 'LinkedInBot', label: 'LinkedIn Post Preview' },
    { name: 'Pinterestbot', label: 'Pinterest Rich Pins' },
    { name: 'Slackbot', label: 'Slack Link Unfurling' },
  ],
  seoAuditBots: [
    { name: 'AhrefsBot', label: 'Ahrefs SEO Crawler' },
    { name: 'SemrushBot', label: 'SEMrush SEO Auditor' },
    { name: 'DotBot', label: 'Moz Open Site Explorer' },
    { name: 'MJ12bot', label: 'Majestic SEO' },
  ],
};

/**
 * Generate standard RFC 9309 robots.txt file content
 */
export function generateRobotsTxt(config: RobotsConfig): string {
  const lines: string[] = [];

  lines.push('# ========================================================');
  lines.push('# Robots.txt Generated by ToolVerse (https://toolverse.app)');
  lines.push('# Compliant with RFC 9309 Robots Exclusion Protocol');
  lines.push('# ========================================================');
  lines.push('');

  for (const group of config.ruleGroups) {
    if (group.name) {
      lines.push(`# --- ${group.name} ---`);
    }

    const agents = group.userAgents && group.userAgents.length > 0 ? group.userAgents : ['*'];
    for (const agent of agents) {
      lines.push(`User-agent: ${agent.trim() || '*'}`);
    }

    // Allows first or Disallows
    if (group.allows && group.allows.length > 0) {
      for (const allow of group.allows) {
        const clean = allow.trim();
        if (clean) lines.push(`Allow: ${clean.startsWith('/') || clean.startsWith('*') ? clean : '/' + clean}`);
      }
    }

    if (group.disallows && group.disallows.length > 0) {
      for (const disallow of group.disallows) {
        const clean = disallow.trim();
        if (clean === '') {
          lines.push(`Disallow:`);
        } else {
          lines.push(`Disallow: ${clean.startsWith('/') || clean.startsWith('*') ? clean : '/' + clean}`);
        }
      }
    } else {
      // If group has no disallows and no allows, default empty Disallow: (allows all)
      if (!group.allows || group.allows.length === 0) {
        lines.push(`Disallow:`);
      }
    }

    if (group.crawlDelay && group.crawlDelay > 0) {
      lines.push(`Crawl-delay: ${group.crawlDelay}`);
    }

    lines.push('');
  }

  // Host directive
  if (config.host && config.host.trim()) {
    lines.push(`Host: ${config.host.trim()}`);
    lines.push('');
  }

  // Sitemaps
  if (config.sitemaps && config.sitemaps.length > 0) {
    lines.push('# Sitemaps');
    for (const sitemap of config.sitemaps) {
      const clean = sitemap.trim();
      if (clean) {
        lines.push(`Sitemap: ${clean}`);
      }
    }
  }

  return lines.join('\n').trim() + '\n';
}

/**
 * Test a URL path against current robots.txt rules according to RFC 9309 longest-match logic
 */
export function testPathAgainstRobots(
  rawPath: string,
  userAgent: string,
  config: RobotsConfig
): PathTestResult {
  let targetPath = rawPath.trim();
  if (!targetPath) targetPath = '/';
  if (!targetPath.startsWith('/')) {
    try {
      const u = new URL(targetPath);
      targetPath = u.pathname + u.search;
    } catch {
      targetPath = '/' + targetPath;
    }
  }

  const cleanAgent = userAgent.trim().toLowerCase();

  // Find most specific rule group matching userAgent
  let matchedGroup: RobotsRuleGroup | null = null;
  let isSpecificMatch = false;

  for (const group of config.ruleGroups) {
    const agents = (group.userAgents || []).map((a) => a.trim().toLowerCase());
    if (agents.includes(cleanAgent)) {
      matchedGroup = group;
      isSpecificMatch = true;
      break;
    }
  }

  // Fallback to wildcard '*'
  if (!matchedGroup) {
    for (const group of config.ruleGroups) {
      const agents = (group.userAgents || []).map((a) => a.trim().toLowerCase());
      if (agents.includes('*')) {
        matchedGroup = group;
        break;
      }
    }
  }

  if (!matchedGroup) {
    return {
      path: targetPath,
      userAgent,
      isAllowed: true,
      matchedDirective: 'Default',
      reason: 'No matching User-agent rule block found in configuration. Access is allowed by default.',
    };
  }

  // Compare matches: RFC 9309 specifies the longest matching pattern takes precedence.
  // If equal length, Allow takes precedence over Disallow.
  let bestMatchLength = -1;
  let bestDirective: 'Allow' | 'Disallow' | null = null;
  let bestPattern = '';

  const testMatch = (pattern: string, directive: 'Allow' | 'Disallow') => {
    let p = pattern.trim();
    if (!p) return;
    if (!p.startsWith('/') && !p.startsWith('*')) p = '/' + p;

    // Convert robots wildcard syntax (* and $) to regex
    const regexStr = '^' + p
      .replace(/[.+?^${}()|[\]\\]/g, '\\$&') // escape special regex except * and $
      .replace(/\*/g, '.*')
      .replace(/\\\$$/, '$'); // keep $ at end if specified

    try {
      const re = new RegExp(regexStr);
      if (re.test(targetPath) || targetPath.startsWith(p.replace(/\*.*$/, ''))) {
        const patternLen = p.length;
        if (patternLen > bestMatchLength) {
          bestMatchLength = patternLen;
          bestDirective = directive;
          bestPattern = p;
        } else if (patternLen === bestMatchLength && directive === 'Allow') {
          // Allow wins tie-break
          bestDirective = 'Allow';
          bestPattern = p;
        }
      }
    } catch {
      // Fallback simple prefix check
      if (targetPath.startsWith(p)) {
        if (p.length > bestMatchLength) {
          bestMatchLength = p.length;
          bestDirective = directive;
          bestPattern = p;
        }
      }
    }
  };

  // Evaluate Allows
  for (const allow of matchedGroup.allows || []) {
    testMatch(allow, 'Allow');
  }

  // Evaluate Disallows
  for (const disallow of matchedGroup.disallows || []) {
    testMatch(disallow, 'Disallow');
  }

  if (bestDirective === 'Disallow') {
    return {
      path: targetPath,
      userAgent,
      isAllowed: false,
      matchedRuleGroup: matchedGroup.name || (isSpecificMatch ? userAgent : '*'),
      matchedDirective: 'Disallow',
      matchedPattern: bestPattern,
      reason: `Blocked by Disallow: ${bestPattern} under User-agent: ${isSpecificMatch ? userAgent : '*'}`,
    };
  } else if (bestDirective === 'Allow') {
    return {
      path: targetPath,
      userAgent,
      isAllowed: true,
      matchedRuleGroup: matchedGroup.name || (isSpecificMatch ? userAgent : '*'),
      matchedDirective: 'Allow',
      matchedPattern: bestPattern,
      reason: `Permitted by Allow: ${bestPattern} under User-agent: ${isSpecificMatch ? userAgent : '*'}`,
    };
  }

  return {
    path: targetPath,
    userAgent,
    isAllowed: true,
    matchedRuleGroup: matchedGroup.name || (isSpecificMatch ? userAgent : '*'),
    matchedDirective: 'Default',
    reason: `No matching Allow or Disallow patterns matched this path. Access is allowed by default.`,
  };
}

/**
 * Audit robots.txt configuration for common SEO mistakes
 */
export function validateRobotsConfig(config: RobotsConfig): RobotsValidationReport {
  const issues: RobotsValidationIssue[] = [];
  let hasTotalBlock = false;

  // 1. Check for total site blocking under wildcard
  for (const group of config.ruleGroups) {
    const isWildcard = (group.userAgents || []).includes('*');
    if (isWildcard) {
      if ((group.disallows || []).includes('/')) {
        const hasAllow = (group.allows || []).some((a) => a === '/' || a === '/*');
        if (!hasAllow) {
          hasTotalBlock = true;
          issues.push({
            type: 'error',
            message: 'Total Site Crawling Blocked: Disallow: / under User-agent: *',
            recommendation:
              'This completely blocks search engines like Google and Bing from crawling and indexing your website. Remove Disallow: / unless this is a private staging server.',
          });
        }
      }
    }
  }

  // 2. Validate Sitemaps
  if (!config.sitemaps || config.sitemaps.length === 0) {
    issues.push({
      type: 'warning',
      message: 'No Sitemap directive specified',
      recommendation:
        'Adding a Sitemap: https://yourdomain.com/sitemap.xml line helps search crawlers quickly discover all your pages and fresh content.',
    });
  } else {
    for (const sm of config.sitemaps) {
      if (!sm.startsWith('http://') && !sm.startsWith('https://')) {
        issues.push({
          type: 'error',
          message: `Invalid Sitemap URL: "${sm}"`,
          recommendation: 'Sitemap directives must be fully-qualified absolute URLs starting with https://.',
        });
      }
    }
  }

  // 3. Validate Disallow & Allow format
  for (const group of config.ruleGroups) {
    for (const d of group.disallows || []) {
      const clean = d.trim();
      if (clean && !clean.startsWith('/') && !clean.startsWith('*')) {
        issues.push({
          type: 'warning',
          message: `Path missing leading slash: "Disallow: ${clean}"`,
          recommendation: `Change to "Disallow: /${clean}". Robots paths should begin with a forward slash.`,
        });
      }
    }
    for (const a of group.allows || []) {
      const clean = a.trim();
      if (clean && !clean.startsWith('/') && !clean.startsWith('*')) {
        issues.push({
          type: 'warning',
          message: `Path missing leading slash: "Allow: ${clean}"`,
          recommendation: `Change to "Allow: /${clean}". Robots paths should begin with a forward slash.`,
        });
      }
    }
  }

  const isValid = issues.filter((i) => i.type === 'error').length === 0;

  return {
    isValid,
    hasTotalBlock,
    sitemapCount: (config.sitemaps || []).length,
    ruleGroupCount: (config.ruleGroups || []).length,
    issues,
  };
}

// ---------------- CURATED PRODUCTION PRESETS ----------------
export const ROBOTS_PRESETS: Array<{
  id: string;
  name: string;
  description: string;
  config: RobotsConfig;
}> = [
  {
    id: 'standard_saas',
    name: 'Standard Safe (SaaS / Web App)',
    description: 'Allows search crawlers, blocks internal API, admin, and cart paths',
    config: {
      ruleGroups: [
        {
          id: 'general',
          name: 'General Search Engine Rules',
          userAgents: ['*'],
          allows: ['/'],
          disallows: ['/admin/', '/api/', '/checkout/', '/cart/', '/account/', '/*.json$'],
        },
      ],
      sitemaps: ['https://toolverse.app/sitemap.xml'],
      host: 'toolverse.app',
    },
  },
  {
    id: 'block_ai_scrapers',
    name: 'Block AI Crawlers & Scrapers',
    description: 'Permits Google/Bing for search, blocks OpenAI, Anthropic, CommonCrawl, ByteDance',
    config: {
      ruleGroups: [
        {
          id: 'search_bots',
          name: 'Search Engines (Allowed)',
          userAgents: ['*'],
          allows: ['/'],
          disallows: ['/admin/', '/api/'],
        },
        {
          id: 'ai_block',
          name: 'AI Training Scrapers (Blocked)',
          userAgents: [
            'GPTBot',
            'ChatGPT-User',
            'CCBot',
            'ClaudeBot',
            'Claude-Web',
            'Google-Extended',
            'Bytespider',
            'PerplexityBot',
            'cohere-ai',
          ],
          allows: [],
          disallows: ['/'],
        },
      ],
      sitemaps: ['https://toolverse.app/sitemap.xml'],
      host: 'toolverse.app',
    },
  },
  {
    id: 'wordpress_woocommerce',
    name: 'WordPress & WooCommerce',
    description: 'Standard WordPress rules: protects wp-admin while permitting admin-ajax',
    config: {
      ruleGroups: [
        {
          id: 'wp_rules',
          name: 'WordPress Rules',
          userAgents: ['*'],
          allows: ['/wp-admin/admin-ajax.php'],
          disallows: ['/wp-admin/', '/wp-includes/', '/checkout/', '/cart/', '/my-account/'],
        },
      ],
      sitemaps: ['https://example.com/sitemap_index.xml'],
      host: 'example.com',
    },
  },
  {
    id: 'nextjs_headless',
    name: 'Next.js App Router Site',
    description: 'Optimized for modern Next.js 14/15 headless web applications',
    config: {
      ruleGroups: [
        {
          id: 'nextjs',
          name: 'Next.js Routing Directives',
          userAgents: ['*'],
          allows: ['/'],
          disallows: ['/api/', '/_next/', '/private/', '/draft/'],
        },
      ],
      sitemaps: ['https://example.com/sitemap.xml'],
      host: 'example.com',
    },
  },
  {
    id: 'private_staging',
    name: 'Staging / Private Dev Server',
    description: 'Complete block to prevent duplicate content penalties on pre-production sites',
    config: {
      ruleGroups: [
        {
          id: 'block_all',
          name: 'Block All Crawlers',
          userAgents: ['*'],
          allows: [],
          disallows: ['/'],
        },
      ],
      sitemaps: [],
    },
  },
];
